import sys
import argparse
import logging
import uvicorn
import asyncio
from fastapi import FastAPI
from contextlib import asynccontextmanager
import threading

import config
from dashboard.server import app, broadcast_sync
from state.event_store import EventStore
from state.aircraft_state import AircraftStateEngine
from state.ground_state import GroundStateEngine
from detection.conflict_detection import ConflictDetector
from detection.emergency_detection import EmergencyDetector
from agent.llm_processor import LLMProcessor
from mcp_server import mcp_app

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# Global instances (in a real app, use dependency injection)
event_store = EventStore()
aircraft_engine = AircraftStateEngine()
ground_engine = GroundStateEngine()
conflict_detector = ConflictDetector(aircraft_engine, ground_engine)
emergency_detector = EmergencyDetector(aircraft_engine, ground_engine)
llm_agent = LLMProcessor()

# Tracking for emergency deduplication
alerted_emergencies = set()

@app.post("/api/resolve-emergency/{entity}")
async def resolve_emergency_api(entity: str):
    """External trigger to clear emergency state for an entity."""
    if entity in alerted_emergencies:
        alerted_emergencies.remove(entity)
        logger.info(f"Externally cleared emergency alert tracking for {entity}")
    
    # Also update state engines to clear flags
    aircraft_engine.update_from_event({
        "callsign": entity,
        "emergency_flag": False
    })
    ground_engine.update_from_event({
        "vehicle_id": entity,
        "emergency_flag": False
    })
    
    # Broadcast state update
    state_snap = {
        "aircraft": aircraft_engine.get_snapshot(),
        "ground": ground_engine.get_snapshot()
    }
    broadcast_sync("state", state_snap)
    
    return {"status": "success", "entity": entity}

app.mount("/mcp", mcp_app)

import time
import uuid

def process_text_transcript(text: str):
    """Core pipeline for processing text transcripts using LLM Agent."""
    if not text.strip(): return
    
    transcript_id = str(uuid.uuid4())
    
    # 1. Immediate raw broadcast before LLM processing
    broadcast_sync("transcript", {"id": transcript_id, "raw": text, "parsed": None})
    
    current_state = {
        "aircraft": aircraft_engine.get_snapshot(),
        "ground": ground_engine.get_snapshot()
    }
    
    # 2. Ask LLM to evaluate transcript and current state
    llm_response = llm_agent.process(text, current_state)
    
    parsed_event = llm_response.parsed_event.model_dump()
    parsed_event["timestamp"] = time.time()
    
    # 3. Update Operational State
    aircraft_engine.update_from_event(parsed_event)
    ground_engine.update_from_event(parsed_event)
    
    # Send Transcripts Update and State to UI
    broadcast_sync("transcript_update", {"id": transcript_id, "raw": text, "parsed": parsed_event})
    
    state_snap = {
        "aircraft": aircraft_engine.get_snapshot(),
        "ground": ground_engine.get_snapshot()
    }
    broadcast_sync("state", state_snap)
    
    # Log events to JSONL
    event_store.log_event(parsed_event, text, state_snap)
    
    # 3. Broadcast Alerts generated by the LLM and Rule-Based Detectors
    all_alerts = [a.model_dump() for a in llm_response.alerts]
    all_alerts.extend(conflict_detector.detect_conflicts())
    all_alerts.extend(emergency_detector.detect_emergencies())
    
    # Identify currently active emergency entities from state to allow re-triggering if cleared
    active_emergency_entities = set()
    for ac in state_snap["aircraft"].values():
        if ac.get("emergency_flag"): active_emergency_entities.add(ac.get("callsign"))
    for gnd in state_snap["ground"].values():
        if gnd.get("emergency_flag"): active_emergency_entities.add(gnd.get("vehicle_id"))
    
    # Clean up alerted_emergencies: remove entities no longer in emergency state
    to_remove = [k for k in alerted_emergencies if k not in active_emergency_entities]
    for k in to_remove:
        alerted_emergencies.remove(k)
        logger.info(f"Cleared emergency alert tracking for {k}")

    for alert_dict in all_alerts:
        # Deduplication for Emergencies
        is_emergency = (
            alert_dict.get("alert_type") == "EMERGENCY_DECLARED" or 
            "emergency" in (alert_dict.get("message") or "").lower() or
            alert_dict.get("severity") == "EMERGENCY"
        )
        
        if is_emergency:
            # Create a unique key (we assume single-entity emergencies for now based on simulator)
            entities = sorted(alert_dict.get("entities", []))
            if not entities: continue
            
            ent_key = entities[0] # Track per primary entity
            if ent_key in alerted_emergencies:
                # Still log it in the event store but skip broadcast
                if "timestamp" not in alert_dict:
                    alert_dict["timestamp"] = time.time()
                event_store.log_alert(alert_dict)
                continue
            
            alerted_emergencies.add(ent_key)
            logger.info(f"Broadcasted INITIAL emergency alert for {ent_key}")

        if "timestamp" not in alert_dict:
            alert_dict["timestamp"] = time.time()
        broadcast_sync("alert", alert_dict)
        event_store.log_alert(alert_dict)

@app.get("/api/plan")
async def get_routing_plan():
    state_snap = {
        "aircraft": aircraft_engine.get_snapshot(),
        "ground": ground_engine.get_snapshot()
    }
    suggestion = llm_agent.generate_plan(state_snap)
    return {"suggestion": suggestion}


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup Phase
    logger.info("Initializing ATC AI Assist Core...")
    import dashboard.server
    dashboard.server._main_loop = asyncio.get_running_loop()
    if app.state.simulate or app.state.simulate_emergency:
        from simulation.radio_simulator import RadioSimulator
        sim_mode = "emergency" if app.state.simulate_emergency else "normal"
        app.state.simulator = RadioSimulator(process_text_transcript, mode=sim_mode, delay_between_calls=1.5)
        app.state.simulator.start()
        logger.info(f"Running in SIMULATION mode ({sim_mode}).")
    else:
        # Load heavy ML models
        from audio.stt_engine import STTEngine
        from audio.speech_listener import SpeechListener
        app.state.stt = STTEngine()
        
        def audio_callback(np_data):
            text = app.state.stt.transcribe(np_data)
            if text:
                logger.info(f"🎤 Heard: {text}")
                process_text_transcript(text)
                
        app.state.listener = SpeechListener(audio_callback)
        
        if app.state.demo_wav:
             logger.info(f"Running offline processing of WAV file: {app.state.demo_wav}")
             threading.Thread(target=app.state.listener.process_wav_file, args=(app.state.demo_wav,), daemon=True).start()
        else:
             logger.info("Starting live microphone listener...")
             app.state.listener.start_microphone()
             
    yield
    
    # Shutdown Phase
    logger.info("Shutting down ATC AI Assist Core...")
    if app.state.simulate or app.state.simulate_emergency:
        app.state.simulator.stop()
    elif hasattr(app.state, 'listener') and app.state.listener:
        app.state.listener.stop()
        
    # Flush remaining logs
    event_store.stop()

app.router.lifespan_context = lifespan

if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser(description="ATC AI Assist System")
    arg_parser.add_argument("--simulate", action="store_true", help="Run with normal scripted simulator instead of audio.")
    arg_parser.add_argument("--simulate-emergency", action="store_true", help="Run with emergency scripted simulator (includes fire/medical/tow response).")
    arg_parser.add_argument("--demo-wav", type=str, help="Run offline using a specified .wav file.")
    args = arg_parser.parse_args()
    
    app.state.simulate = args.simulate
    app.state.simulate_emergency = args.simulate_emergency
    app.state.demo_wav = args.demo_wav
    
    if args.demo_wav and (args.simulate or args.simulate_emergency):
         logger.error("Cannot use simulation arguments and --demo-wav at the same time.")
         sys.exit(1)
         
    if args.simulate and args.simulate_emergency:
         logger.error("Cannot use both --simulate and --simulate-emergency at the same time.")
         sys.exit(1)
         
    logger.info(f"Starting API Server on http://{config.HOST}:{config.PORT}")
    uvicorn.run(app, host=config.HOST, port=config.PORT, log_level="warning")
